// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: common/common.proto

/* eslint-disable */

export const protobufPackage = "common";

export enum SortOrders {
  ASC = "ASC",
  DESC = "DESC",
}

export interface Empty {
}

export interface StatusResponse {
  status: boolean;
}

export interface FilterOffset {
  count?: number | undefined;
  page?: number | undefined;
}

export const COMMON_PACKAGE_NAME = "common";
