// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: main/main.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty, StatusResponse } from "../common/common";

export const protobufPackage = "main";

export const MAIN_PACKAGE_NAME = "main";

export interface NotificationAppServiceClient {
  getStatus(request: Empty, metadata: Metadata, ...rest: any): Observable<StatusResponse>;
}

export interface NotificationAppServiceController {
  getStatus(
    request: Empty,
    metadata: Metadata,
    ...rest: any
  ): Promise<StatusResponse> | Observable<StatusResponse> | StatusResponse;
}

export function NotificationAppServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getStatus"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NotificationAppService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NotificationAppService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_APP_SERVICE_NAME = "NotificationAppService";
