export const ValidationErrors = {
  IN: "validation.in",
  ENUM: "validation.enum",
  ARRAY_FORMAT: "validation.array_format",
  STRING_FORMAT: "validation.string_format",
  EMAIL_FORMAT: "validation.email_format",
  NUMBER_FORMAT: "validation.number_format",
  DECIMAL_FORMAT: "validation.decimal_format",
  DATE_FORMAT: "validation.date_format",
  BOOLEAN_FORMAT: "validation.boolean_format",
  PHONE_FORMAT: "validation.phone_format",
  UUID_FORMAT: "validation.uuid_format",
  URL_FORMAT: "validation.url_format",
  JSON_FORMAT: "validation.json_format",
  TZ_FORMAT: "validation.tz_format",
  BASE64_FORMAT: "validation.base64_format",
  CHOICE_TYPE_FORMAT: "validation.choice_type_format",
  EMPTY: "validation.empty",
  NOT_EMPTY: "validation.not_empty",
  MAX_LENGTH: "validation.max_length",
  LENGTH: "validation.length",
  MAX: "validation.max",
  MIN: "validation.min",
  UINT8_ARRAY_MAX_LENGTH: "validation.uint8_array_max_length",
};
